@startuml
|User|
start

: Login ;
:Input username & password;

|System|
if (Valid credentials?) then (yes)
  :Redirect to Dashboard;
endif

|User|
: Analysis;
:View list of Analysis;

if (Create New Analysis?) then (yes)
  :Input Analysis name;
  
  |System|
  :Save to database;
endif

|User|
:Select an Analysis;
:Click "Edit";

|System|
:Redirect to Input Data ;

|User|
:Input Criteria;

|System|
:Save Criteria to DB;

|User|
:Input Alternative (via Map);

|System|
:Save Alternative to DB;

|User|
:Lihat/Hapus data Kriteria/Alternatif;

|System|
:Fetch/Delete data from DB;

|User|
:Click 'Process This Data';

|System|
:Redirect to AHP Process ;

|User|
:Input Pairwise Kriteria;
:Input Pairwise Alternatif;
:Click Process;

|System|
:Calculate and Save Result;

:Redirect to Result ;

|User|
:View Chart (Ranking);
:View Calculation History (CI, CR, Lambda);
:Return to Manage Analysis ;

:Click "Mapping";

|System|
: Mapping ;

|User|
:Edit Area in MAP;
:Click "Take Area";

|System|
:Save Image;

stop
@enduml
