@startuml
start

:User opens Login Page;
:Input username & password;
-> [Valid credentials]
:Redirect to Dashboard;

:User accesses Manage Analysis;
:View list of Analysis;
if (Create New Analysis?) then (yes)
  :Input Analysis name;
  :Save to database;
endif

:Select an Analysis;
split
  :Click "Edit";
  :Redirect to Input Data Page;

  :Input Criteria;
  :Save Criteria to DB;

  :Input Alternative (via Map);
  :Save Alternative to DB;

  :Lihat/Hapus data Kriteria/Alternatif;
  :Fetch/Delete data from DB;

  :Click 'Process This Data';
  :Redirect to AHP Process Page;

  :Input Pairwise Kriteria;
  :Input Pairwise Alternatif;
  :Click Process;
  :Calculate and Save Result;

  :Redirect to Result Page;
  :View Chart (Ranking);
  :View Calculation History (CI, CR, Lambda, etc);
  :view Manage Analysis Page;
endsplit

  :Click "Mapping";
  :Open Mapping Page;
  :Edit Area in MAP;
  :Click "Take Area";
  : Save Image;

stop
@enduml