@startuml
actor Admin
database Database

boundary "Dashboard" as Dashboard
boundary "Manage Analysis Page" as AnalysisPage
boundary "Input Data Page" as InputPage

== Analysis Workflow ==
Admin -> AnalysisPage : Open Manage Analysis Page
AnalysisPage -> Database : Fetch List of Analysis
Database --> AnalysisPage : Return Analysis List
Admin -> AnalysisPage : Click "Create Analysis"
AnalysisPage -> InputPage : Redirect
@enduml
