@startuml
actor Admin

boundary "Analysis Page" as AnalysisPage
boundary "Input Data Page" as InputPage
boundary "AHP Page" as AHPPage
database Database as Database

== Input Kriteria/Alternatif ==
Admin -> InputPage : Input Kriteria
InputPage -> Database : Save Kriteria
Admin -> InputPage : Input Alternatif via Map
InputPage -> Database : Save Alternatif
Admin -> InputPage : Lihat/Hapus Kriteria/Alternatif
InputPage -> Database : Fetch/Delete Data
Admin -> InputPage : Click \"Process This Data\"
InputPage -> AHPPage : Redirect to Pairwise
@enduml
