@startuml
actor User

boundary "Analysis Page" as AnalysisPage
boundary "Input Data Page" as InputPage
boundary "AHP Page" as AHPPage
database Database as Database

== Input Kriteria/Alternatif ==
User -> InputPage : Input Kriteria
InputPage -> Database : Save Kriteria
User -> InputPage : Input Alternatif via Map
InputPage -> Database : Save Alternatif
User -> InputPage : Lihat/Hapus Kriteria/Alternatif
InputPage -> Database : Fetch/Delete Data
User -> InputPage : Click \"Process This Data\"
InputPage -> AHPPage : Redirect to Pairwise
@enduml
