@startuml
actor Admin


boundary "Input Data Page" as InputPage
boundary "AHP Page" as AHPPage
boundary "Result Page" as ResultPage
database Database as Database

== Proses AHP ==
Admin -> InputPage : Click "Process This Data"
InputPage -> AHPPage : Redirect
Admin -> AHPPage : Input Pairwise Kriteria
Admin -> AHPPage : Input Pairwise Alternatif
Admin -> AHPPage : Click Process
AHPPage -> Database : Simpan Hasil Perhitungan
AHPPage -> ResultPage : Redirect
@enduml