@startuml
actor User


boundary "AHP Page" as AHPPage
boundary "Result Page" as ResultPage
database Database as Database

== Result Workflow ==
User -> ResultPage : View Chart (Ranking)
ResultPage -> Database : Fetch Ranking & CI/CR Details
User -> ResultPage : Save to DB (if not saved)
ResultPage -> Database : Store Final Result
User -> ResultPage : Click Export to PDF
ResultPage -> ResultPage : Screenshot & Download PDF

@enduml