@startuml
actor Admin


boundary "AHP Page" as AHPPage
boundary "Result Page" as ResultPage
database Database as Database

== Result Workflow ==
Admin -> ResultPage : View Chart (Ranking)
ResultPage -> Database : Fetch Ranking & CI/CR Details
Admin -> ResultPage : Save to DB (if not saved)
ResultPage -> Database : Store Final Result
Admin -> ResultPage : Click Export to PDF
ResultPage -> ResultPage : Screenshot & Download PDF

@enduml