@startuml
actor Admin

boundary "Result Page" as ResultPage
boundary "Mapping Page" as MappingPage
boundary "Manage Account Page" as AccountPage
database Database as Database

== Mapping Workflow ==
Admin -> MappingPage : Open Mapping
MappingPage -> Database : Fetch Geo Data (if any)
Admin -> MappingPage : Edit Map Area (GeoMan)
Admin -> MappingPage : Click "Take Area"
MappingPage -> MappingPage : Screenshot Map
MappingPage -> Admin : Download
