@startuml
left to right direction
actor "User" as SPK

rectangle My-SPK {
  usecase "Analysis" as UC1
  usecase "Manage Analysis" as UC2
  usecase "Manage Account" as UC3
}

SPK --> UC1
SPK --> UC2
SPK --> UC3
@enduml
