@startuml
left to right direction
actor "User" as SPK

rectangle "Login Workflow" {
  usecase "Login" as L1
  usecase "Input Username" as L1a
  usecase "Input Password" as L1b
  usecase "Autentikasi User" as L1c
  usecase "Redirect to Dashboard" as L1d
  usecase "Tampilkan Error Login" as L1e
}

SPK --> L1
L1 --> L1a : <<include>>
L1 --> L1b : <<include>>
L1 --> L1c : <<include>>

L1c --> L1d : <<extend>>
L1c --> L1e : <<extend>>
@enduml
