@startuml
left to right direction
actor "User" as SPK

rectangle "Manage Analysis Workflow" {
  usecase "Lihat Tabel Analysis" as M1
  usecase "Show result Analysis (if user save)" as M2
  usecase "Edit calculation/kriteria/alternatif" as M3
  usecase "Delete Analysis" as M4
  usecase "mapping terhadap alternatif rank pertama" as M5
}

SPK --> M1
M1 --> M2 : <<extend>>
M1 --> M3 : <<extend>>
M1 --> M4 : <<extend>>
M1 --> M5 : <<extend>>
@enduml
