@startuml
top to bottom direction

actor "User" as SPK

rectangle "Manage Account Workflow" {
  usecase "Akses Halaman\nManage Account" as A1
  usecase "Ganti Username/\nPassword" as A2
  usecase "Verifikasi \n(via Modal)" as A3
  usecase "Update Akun" as A4
}

SPK --> A1
A1 --> A2 : <<include>>
A2 --> A3 : <<include>>
A3 --> A4 : <<include>>
@enduml
