@startuml
left to right direction
actor "User" as SPK

rectangle "Process AHP Workflow" {
  usecase "Process AHP" as P1

  usecase "Pairwise Comparison Kriteria" as P1a
  usecase "Pairwise Comparison Alternatif" as P1b

  usecase "Process to Result" as P2
}

SPK --> P1
P1 --> P1a : <<include>>
P1 --> P1b : <<include>>
P1 --> P2 : <<extend>>
@enduml
