@startuml
left to right direction
actor "User" as SPK

rectangle "Input Data Workflow" {
  usecase "Input Data" as D1

  usecase "Input Kriteria" as D1a
  usecase "Input Alternatif via Map" as D1b
  usecase "Lihat Data Kriteria/Alternatif" as D1c
  usecase "Hapus Kriteria/Alternatif" as D1d

  usecase "Process AHP" as D2
}

SPK --> D1
D1 --> D1a : <<include>>
D1 --> D1b : <<include>>
D1 --> D1c : <<include>>
D1 --> D1d : <<include>>
D1 --> D2 : <<extend>>
@enduml
