@startuml
left to right direction
actor "User" as SPK

rectangle "Result Workflow" {
  usecase "Lihat Hasil Ranking (Chart)" as R1
  usecase "Lihat Detail Perhitungan (CI, CR, dll)" as R2
  usecase "Simpan Hasil ke Database" as R3
  usecase "Export ke PDF" as R4
}

SPK --> R1
SPK --> R2
SPK --> R3
SPK --> R4
@enduml
