@startuml
left to right direction
actor "User" as SPK

rectangle "Analysis Workflow" {
  usecase "Create Analysis" as A1
  usecase "Lihat Daftar Analysis" as A1a
  usecase "Input Data" as A2
}

SPK --> A1
A1 --> A1a : <<include>>
A1a --> A2 : <<extend>>

@enduml
